### ISSUE TITLE
How to add a Sleeping End Node to the Controller

### ISSUE THREAD

**Issue by PaulNoto** [jefffhaynes/XBee#11]
Since Sleeping End Nodes won't show up during Network Discovery, I have to add them to the Controller manually. I didn't find any reference to this in the ReadMe file. After your last change to the Library, the way I was doing it stopped working. The Only way I was able to figure out, now, was to make a change to the Source Code, by making XBeeController.CreateNode Public. That allows me to add a Sleeping End Node after Network Discovery and also it's Event Handler.

await controller.DiscoverNetwork();

AddLog( "END network discovery" );

AddLog( "Adding Node End_Grove" );

endGrove = await Task.FromResult( controller.CreateNode( HardwareVersion.XBee24C, new NodeAddress( new LongAddress( ulong.Parse( "0013A20040F7829A", System.Globalization.NumberStyles.HexNumber ) ), new ShortAddress( ushort.Parse( "0A90", System.Globalization.NumberStyles.HexNumber ) ) ) ) );

endGrove.SampleReceived += ( node, sample ) => AddLog( cntr1++.ToString() + " " + DateTime.Now.ToShortTimeString() + " End_Grove Sample: " + sample.DigitalSampleState.ToString() );

AddLog( "End_Grove Added to controller" );

Is there a way to do this that I didn't find?

**Comment by jefffhaynes** [comment]
Can you just call GetNodeAsync on the controller?






On Sun, Apr 24, 2016 at 2:38 PM -0700, "PaulNoto" <notifications@github.com> wrote:












Since Sleeping End Nodes won't show up during Network Discovery, I have to add them to the Controller manually. I didn't find any reference to this in the ReadMe file. After your last change to the Library, the way I was doing it stopped working. The Only way I was able to figure out, now, was to make a change to the Source Code, by making XBeeController.CreateNode Public. That allows me to add a Sleeping End Node after Network Discovery and also it's Event Handler.



await controller.DiscoverNetwork();



AddLog( "END network discovery" );



AddLog( "Adding Node End_Grove" );



endGrove = await Task.FromResult( controller.CreateNode( HardwareVersion.XBee24C, new NodeAddress( new LongAddress( ulong.Parse( "0013A20040F7829A", System.Globalization.NumberStyles.HexNumber ) ), new ShortAddress( ushort.Parse( "0A90", System.Globalization.NumberStyles.HexNumber ) ) ) ) );



endGrove.SampleReceived += ( node, sample ) => AddLog( cntr1++.ToString() + " " + DateTime.Now.ToShortTimeString() + " End_Grove Sample: " + sample.DigitalSampleState.ToString() );



AddLog( "End_Grove Added to controller" );



Is there a way to do this that I didn't find?

**Comment by PaulNoto** [comment]
That is what I was doing before the last change to your library. Now, I get an Unhandled Timeout exception.

**Comment by jefffhaynes** [comment]
Oh, of course. It's trying to get the specific version of the remote node. Ok, I'll fix it. 






On Sun, Apr 24, 2016 at 3:22 PM -0700, "PaulNoto" <notifications@github.com> wrote:












That is what I was doing before the last change to your library. Now, I get an Unhandled Timeout exception.

**Comment by PaulNoto** [comment]
Tested. I can use my old XBees now. Thanks Jeff.
